language: python
matrix:
  include:
  - os: linux
    python: 2.7
  - os: linux
    python: 3.6
    env: BUILDDOC=1
  - os: linux
    python: 3.8

install:
  - pip install numpy pyparsing pytest "pytest-cov<2.6" sphinx matplotlib
  - pip install .

script:
  - pytest -v
  - if [ -n "$BUILDDOC" ]; then make -j 4 -C doc/sphinx SPHINXOPTS="-W --keep-going" html; fi
